name: Patricia Hita - Fotografía
favicon: null
layout_spectrum: 0.6713590859435499
typography_spectrum: 0.8408299176953733
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4967586926650256
  lightness: 0.3449661140330136
  saturation: 0.5093516851775348
  rhythmicContrast: 0.2363866213709116
purpose: []
